### ISSUE TITLE
Consider moving the silverware cookbook to an independent repo

### ISSUE THREAD

**Issue by abecciu** [infochimps-labs/ironfan#264] opened 2013-03-18 22:01 UTC
I find the silverware cookbook very interesting and useful. But I'm not interested in the rest of the ironfan-patry cookbooks. Moving it to its own repo would make it easier to include in other chef repos, and I think it could also gain more visibility and adoption.

**Comment by temujin9** [comment] 2013-03-20 17:20
So, this is a semi-recurrent discussion. The problem is multi-faceted:
- We'd love to see more visibility and adoption of Ironfan components, even if you don't want to go whole hog. Unfortunately, you're in a tertiary user group, after our enterprise clients and full-stack open-source users, so it's harder to prioritize issues that only hit you.
- We really like the pantry approach for internal development. It's got a number of advantages in ease of use, and only some small impedance mismatch with the rest of the Chef world for obvious drawback.
- The last time we tried to wire together per-cookbook repos and pantry repos, via a git subtree setup, we encountered severe code drift, which complicated accepting several pull requests. Admittedly, automation could easily help this.
- You can't turn off Github pull requests on a repo. The subtree setup would have to be bidirectional, which gets messy real quick. Otherwise we'd have to manually reject all comers to the per-cookbook side, forcing them to use the pantries anyway.
- We're a small shop, and haven't devoted enough time to connecting our cookbook development cycle into the Opscode Community cookbooks. I'd love to automate this, once we do.

Addressing that last point seems like the simplest way to handle this. We've got an internal ticket open about it; I'll link this there, to point out a user demand we could be supplying. I'm going to close this ticket; there's really nothing actionable at the moment, and I like to keep the issues lists trim.

Thank you for pointing out the need!

**Closed as completed by temujin9** 2013-03-20 17:20 UTC
Labels: important
