### ISSUE TITLE
-V option doesn't give me a stack trace

### ISSUE THREAD

**Issue by LeeGraber** [infochimps-labs/ironfan#252] opened 2013-02-14 00:35 UTC
I have an issue where doing bundle exec knife cluster kick <cluster-name> gives:
Exception: NoMethodError: undefined method `each' for nil:NilClass

I do not know why. On another cluster definition it works fine. Perhaps the difference is that the cluster where it works was just built whereas the cluster it is failing on already existed and used to work just fine. I have moved forward versions of ironfan and chef but need to still manage existing clusters. I am opening a separate issue on that but if -V gave me a stack trace, I would have an easier time debugging on my own. :)

**Comment by temujin9** [comment] 2013-02-14 16:44
Hey, Lee. This is actually a known issue with bundle exec: it will swallow flags if the command is not enclosed in quotes, like so: `bundle exec "knife cluster kick -V"`.

I'm hopeful that I can quickly pull the "drop into bundle mode" code I've got in other Rakefiles into the knife plugin (which should also solve the problem, by removing the necessity of running inside of `bundle exec`) My plate's just been very full lately.

**Comment by temujin9** [comment] 2013-02-14 16:47
Closing this as a duplicate of #246.

**Closed as completed by temujin9** 2013-02-14 16:47 UTC

**Comment by LeeGraber** [comment] 2013-02-14 17:18
Thanks. I didn't know that. I will keep that in mind from now on. :) I
eventually just edited my local copy to get the stack and found a place and
error came from ssh-multi and was because I didn't have the required ssh
key in my local list. Of course. ;)
