### ISSUE TITLE
Reminder to Nate: Rundeck integration

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#71] opened 2011-11-30 07:22 UTC
Per conversations today, opening this to track the release of Nate's rundeck cookbook.

I'd like to help work on the DSL to allow services to wait for a resource/be orchestrated by rundeck.

**Comment by mrflip** [comment] 2011-11-30 16:13
(closing dupe of #72)

**Closed as completed by mrflip** 2011-11-30 16:13 UTC
