### ISSUE TITLE
Ironfan fog_connection region can only be set via Chef::Config

### ISSUE THREAD

**Issue by gwilton** [infochimps-labs/ironfan#134] opened 2012-05-10 20:44 UTC
Can the fog connection parameters be set by cloud.region or face.cloud.region instead of Chef::Config. This will allow for cluster to control which regions the facets/cloud are deployed to.

module Ironfan

  def self.fog_connection
    @fog_connection ||= Fog::Compute.new({
        :provider              => 'AWS',
        :aws_access_key_id     => Chef::Config[:knife][:aws_access_key_id],
        :aws_secret_access_key => Chef::Config[:knife][:aws_secret_access_key],
        :region                => Chef::Config[:knife][:region]
      })
  end

**Comment by temujin9** [comment] 2012-05-14 15:03
This isn't yet possible, but I'll mark it for consideration as we rework the cluster parsing internals. I suspect that the changes necessary will make it a longer-term project.

**Comment by temujin9** [comment] 2012-09-13 18:59
This is a duplicate of #91: we'll tackle it there.

**Closed as completed by temujin9** 2012-09-13 18:59 UTC
